language: ruby
rvm: 2.6
jdk: openjdk8

install:
   - gem update --system
   - gem --version
   - rm Gemfile.lock
   - bundle install
   - gem install html-proofer
script:
  - jekyll build
  - htmlproofer --url-ignore "/#.*/,/^\/index$/,/www\.it24hrs\.com/,/ffc\.in\.th/,/^\/news$/" ./_site --check-html
env:
  global:
    -NOKOGIRI_USE_SYSTEM_LIBRARIES=true
