language: ruby
rvm: 2.6.3
jdk: oraclejdk8

install:
   - gem update --system
   - gem --version
   - bundle install
script:
  - bundle exec jekyll build
  - htmlproofer --url-ignore "/#.*/,/^\/index$/,/www\.it24hrs\.com/,/ffc\.in\.th/,/^\/news$/" ./_site --check-html
env:
  global:
    -NOKOGIRI_USE_SYSTEM_LIBRARIES=true
